import "./../globals.css";

import Sidebar from "@/components/Sidebar";
import { getUserData } from "@/lib/user-utils";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AuthLayout({ children }) {
  const userData = await getUserData();

  return (
    <div
      className="flex"
      style={{
        backgroundImage:
          "linear-gradient(-125deg, var(--background) 20%, #334155 100%)",
      }}
    >
      <div className="flex-1">{children}</div>
    </div>
  );
}
